version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_db
    networks:
      - msa-network

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - msa-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - discovery-service
    ports:
      - "8080:8080"
    networks:
      - msa-network

  ticket-service:
    build:
      context: .
      dockerfile: ticket-service/Dockerfile
    container_name: ticket-service
    depends_on:
      - discovery-service
    ports:
      - "8081:8081"
    networks:
      - msa-network

  ticketstock-service:
    build:
      context: .
      dockerfile: ticketStock-service/Dockerfile
    container_name: stock-service
    depends_on:
      - discovery-service
    ports:
      - "8082:8082"
    networks:
      - msa-network

  reservation-service:
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    container_name: reservation-service
    depends_on:
      - discovery-service
    ports:
      - "8083:8083"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
