server:
  port: 8082

spring:
  application:
    name: stock-service

  datasource:
    url: jdbc:mysql://mysql:3306/ticket_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ticketing-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    cors: true
