version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ticketing-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing_db
    ports:
      - "3308:3306"
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: