server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

  
management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    urls[0]:
      name: ticket-service
      url: http://localhost:8080/v3/api-docs/ticket
    urls[1]:
      name: ticketStock-service
      url: http://localhost:8080/v3/api-docs/stock
    urls[2]:
      name: reservation-service
      url: http://localhost:8080/v3/api-docs/reservation
